### ISSUE TITLE
Privacy manifest files

### ISSUE THREAD

**Issue by hatched-krzysztof** [RadiusNetworks/flybuy-ios#12]
Starting from May 1st, every app and SDK needs to provide a privacy manifest stating the reason why it needs to access specific APIs. Is the Flybuy SDK affected by this requirement?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by botnerd** [comment]
We're working on this now, and will have a release soon to address this.

**Comment by botnerd** [comment]
This was fixed in the 2.9.0 release of the SDK. Please let us know if you run into any issues.
