### ISSUE TITLE
Deadlock on main thread

### ISSUE THREAD

**Issue by hatched-krzysztof** [RadiusNetworks/flybuy-ios#13]
When `didRegisterForRemoteNotificationsWithDeviceToken` has been called by OS we are calling `FlyBuy.Core.updateAPNPushToken(deviceToken)`

We have noticed that if `didRegisterForRemoteNotificationsWithDeviceToken` was called multiple times with the same device token Flybuy SDK blocks main thread and app becomes unresponsive.

Here is screenshot from debugger. It looks that semaphore is waiting on main thread and signal has never been called.
<img width="482" alt="Screenshot 2024-04-08 at 12 57 21" src="https://github.com/RadiusNetworks/flybuy-ios/assets/76966254/aeed8744-bbe6-426a-a288-0488c02c6c37">

**Comment by botnerd** [comment]
Thank you for reporting this. We'll take a look.

**Comment by botnerd** [comment]
We have identified the issue and will have a fix in the next SDK release.

**Comment by botnerd** [comment]
This has been fixed in the [2.9.1 release](https://github.com/RadiusNetworks/flybuy-ios/releases/tag/2.9.1). Please let us know if you have any additional issues.
