### ISSUE TITLE
Update copy to remove curbside language on "Arrived" screen

### ISSUE THREAD

**Issue by emilyrwhite** [RadiusNetworks/flybuy-ios#3]
![Screen Shot 2020-07-07 at 3 05 56 PM](https://user-images.githubusercontent.com/53627058/86830222-71194c00-c063-11ea-9bf7-ea637aa24e4c.png)

Current:

> We will be out shortly with your order. Please tap below when your have received it to mark it as complete in your orders list.

New:

> Tap "I'm done" once you've received your order.

@greencoder

**Comment by greencoder** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-07-07 at 13 06 47](https://user-images.githubusercontent.com/239861/86830430-ec263680-c052-11ea-8960-5f5780d7a396.png)
