### ISSUE TITLE
Support SwiftPackageManager

### ISSUE THREAD

**Issue by joshuapoq** [RadiusNetworks/flybuy-ios#4]
SwiftPackageManager has gained support for binary targets which will officially release in the next few weeks. Currently the method of adoption of the FlyBuy framework is manual and fairly cumbersome with regards to updates.

Please can you support SwiftPackageManager from Xcode 12 onwards?

**Comment by botnerd** [comment]
We just released a public alpha of our 2.0 SDK that uses Swift 5.3 and Swift Package Manager. The 2.0 SDK has all the same functionality of the 1.0 SDK, but has been structured a bit to make future enhancements easier. There's documentation including a migration guide at https://www.radiusnetworks.com/developers/flybuy/#/. Feel free to try it out and let us know if you have any issues.
