### ISSUE TITLE
Swift 5.3

### ISSUE THREAD

**Issue by chuckzee** [RadiusNetworks/flybuy-ios#6]
Can we get an update of the SDK to Swift 5.3?

https://swift.org/blog/swift-5-3-released/

**Comment by botnerd** [comment]
We just released a public alpha of our 2.0 SDK that uses Swift 5.3 and Swift Package Manager. The 2.0 SDK has all the same functionality of the 1.0 SDK, but has been structured a bit to make future enhancements easier. There's documentation including a migration guide at https://www.radiusnetworks.com/developers/flybuy/#/. Feel free to try it out and let us know if you have any issues.
