### ISSUE TITLE
iOS FlyBuy v2.0.x migration

### ISSUE THREAD

**Issue by GabrielMassana** [RadiusNetworks/flybuy-ios#8]
Hello,

I'm migrating a project to v2.0.x

How can I migrate this v1 call?

`FlyBuy.stopLocationUpdates()`

Thx

**Comment by botnerd** [comment]
Thank you for the feedback. The location manager is now part of the `pickup` module. `FlyBuyPickup.Manager.shared.stop()` can be used in place of `FlyBuy.stopLocationUpdates()`. Note that prior to the stable release, we will be making updates so this method no longer needs to be called directly. The SDK will keep track of orders and automatically stop the location updates.

Please let us know if you have any additional questions or issues.
