### ISSUE TITLE
Xcode 12 + SPM 'IPA Processing Failed'

### ISSUE THREAD

**Issue by JoshyMW** [RadiusNetworks/flybuy-ios#9]
## What did you do?

1. Have an extension with your app so it generates the `PlugIns` directory within the output app.
2. Used SPM to add the FlyBuy frameworks with Xcode 12.
3. Archived and went to distribute app (validate doesn't show the error).

## What happened instead?

Failed due to Xcode 12 issue with SPM where it embeds the frameworks into all the things when it shouldn't be doing this.

This is slightly different to other SDKs where the issue is present for their static frameworks. FlyBuy are dynamic frameworks so should be embedded but not everywhere.

## Workaround

This is a similar [issue to FirebaseAnalytics](https://github.com/firebase/firebase-ios-sdk/issues/6472). Whilst I don't share the same view that this is wholly and Xcode issue, there is a workaround and I would advise watching the previously linked issue.

To fix this:
1. Go to **Edit Scheme...**
2. Expand **Build**
3. Go to **Post-actions**
4. Press the **+** in the bottom left corner
5. Select your app from the dropdown for **Provide build settings from**
6. Add the following code

```
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Plugins/FlyBuy.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Plugins/FlyBuyNotify.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Plugins/FlyBuyPickup.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Plugins/FlyBuyPresence.framework"
```

_Note: You can also give this script a nice name (by double tapping the name) but Xcode is a bit rubbish at editing it as the text goes invisible._

**Comment by botnerd** [comment]
Thank you for providing these details. We'll take a look and see what we can do.

**Comment by stoqn4opm** [comment]
For those of you who come later, i had the same IPA processing failure in XCode 12.4 on another project using many other dependancies, but not this one. XCode 12.5 beta 3, exports the archive just fine for me

**Comment by botnerd** [comment]
Thank you for this additional information.

@JoshyMW Let us know if updated XCode resolves the issue for you.

**Comment by botnerd** [comment]
Closing this issue since updating Xcode should resolve the issue.
